In [1]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.4.4


In [2]:
arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(arr1)

1D Array:
[10 20 30 40 50]


In [3]:
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("2D Array:")
print(arr2)

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [4]:
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("3D Array:")
print(arr3)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
print("1D Array")
print("Dimensions:", arr1.ndim)
print("Shape:", arr1.shape)
print("Data Type:", arr1.dtype)
print("Size:", arr1.size)

print("\n2D Array")
print("Dimensions:", arr2.ndim)
print("Shape:", arr2.shape)
print("Data Type:", arr2.dtype)
print("Size:", arr2.size)

print("\n3D Array")
print("Dimensions:", arr3.ndim)
print("Shape:", arr3.shape)
print("Data Type:", arr3.dtype)
print("Size:", arr3.size)

1D Array
Dimensions: 1
Shape: (5,)
Data Type: int64
Size: 5

2D Array
Dimensions: 2
Shape: (3, 3)
Data Type: int64
Size: 9

3D Array
Dimensions: 3
Shape: (2, 2, 3)
Data Type: int64
Size: 12


In [6]:
print("1D Array:", arr1)

print("First element:", arr1[0])
print("Third element:", arr1[2])
print("Last element:", arr1[-1])

print("\n2D Array:")
print(arr2)

print("First row, first column:", arr2[0, 0])
print("Second row, third column:", arr2[1, 2])
print("Third row, second column:", arr2[2, 1])

1D Array: [10 20 30 40 50]
First element: 10
Third element: 30
Last element: 50

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
First row, first column: 10
Second row, third column: 60
Third row, second column: 80


In [7]:
print("Original Array:")
print(arr1)

print("\nFirst three elements:")
print(arr1[:3])

print("\nElements from index 2:")
print(arr1[2:])

print("\nElements from index 1 to 3:")
print(arr1[1:4])

Original Array:
[10 20 30 40 50]

First three elements:
[10 20 30]

Elements from index 2:
[30 40 50]

Elements from index 1 to 3:
[20 30 40]


In [8]:
print("First two rows:")
print(arr2[:2])

print("\nFirst two columns:")
print(arr2[:, :2])

print("\nFirst two rows and columns:")
print(arr2[:2, :2])

First two rows:
[[10 20 30]
 [40 50 60]]

First two columns:
[[10 20]
 [40 50]
 [70 80]]

First two rows and columns:
[[10 20]
 [40 50]]


In [9]:
zeros_array = np.zeros((3, 4))

print("Array of zeros:")
print(zeros_array)

Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
ones_array = np.ones((3, 4))

print("Array of ones:")
print(ones_array)

Array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
arr_range = np.arange(1, 11)

print("Numbers from 1 to 10:")
print(arr_range)

print("\nNumbers from 0 to 20 with step 5:")
print(np.arange(0, 21, 5))

Numbers from 1 to 10:
[ 1  2  3  4  5  6  7  8  9 10]

Numbers from 0 to 20 with step 5:
[ 0  5 10 15 20]


In [13]:
arr_linear = np.linspace(0, 10, 6)

print("6 equally spaced values between 0 and 10:")
print(arr_linear)

6 equally spaced values between 0 and 10:
[ 0.  2.  4.  6.  8. 10.]


In [14]:
arr = np.arange(1, 13)

print("Original Array:")
print(arr)

reshaped_array = arr.reshape(3, 4)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print("Original 2D Array:")
print(arr2)

flat_array = arr2.flatten()

print("\nFlattened Array:")
print(flat_array)

Original 2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Flattened Array:
[10 20 30 40 50 60 70 80 90]


In [16]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)

print("\nAddition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDivision:")
print(a / b)

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition:
[11 22 33 44]

Subtraction:
[ 9 18 27 36]

Multiplication:
[ 10  40  90 160]

Division:
[10. 10. 10. 10.]


In [17]:
numbers = np.array([1, 4, 9, 16, 25])

print("Original Array:")
print(numbers)

print("\nSquare Root:")
print(np.sqrt(numbers))

print("\nSquare:")
print(np.square(numbers))

print("\nExponential:")
print(np.exp(numbers))

Original Array:
[ 1  4  9 16 25]

Square Root:
[1. 2. 3. 4. 5.]

Square:
[  1  16  81 256 625]

Exponential:
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [18]:
marks = np.array([50, 60, 70, 80, 90])

print("Original Marks:")
print(marks)

print("\nAfter adding 5 marks:")
print(marks + 5)

print("\nAfter multiplying by 2:")
print(marks * 2)

print("\nAfter subtracting 10:")
print(marks - 10)

Original Marks:
[50 60 70 80 90]

After adding 5 marks:
[55 65 75 85 95]

After multiplying by 2:
[100 120 140 160 180]

After subtracting 10:
[40 50 60 70 80]


In [19]:
marks = np.array([45, 67, 82, 35, 90, 56, 76])

print("Marks:")
print(marks)

print("\nMarks greater than or equal to 60:")
print(marks[marks >= 60])

print("\nMarks greater than 75:")
print(marks[marks > 75])

print("\nMarks less than 50:")
print(marks[marks < 50])

Marks:
[45 67 82 35 90 56 76]

Marks greater than or equal to 60:
[67 82 90 76]

Marks greater than 75:
[82 90 76]

Marks less than 50:
[45 35]


In [20]:
marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [90, 95, 88]
])

bonus = np.array([5, 3, 2])

print("Original Marks:")
print(marks)

print("\nBonus Marks:")
print(bonus)

result = marks + bonus

print("\nAfter Broadcasting:")
print(result)

Original Marks:
[[70 80 90]
 [60 75 85]
 [90 95 88]]

Bonus Marks:
[5 3 2]

After Broadcasting:
[[75 83 92]
 [65 78 87]
 [95 98 90]]


In [21]:
marks = np.array([50, 60, 70, 80, 90])

print("Marks:")
print(marks)

print("\nSum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Median:", np.median(marks))

Marks:
[50 60 70 80 90]

Sum: 350
Mean: 70.0
Minimum: 50
Maximum: 90
Median: 70.0


In [22]:
marks = np.array([
    [80, 70, 90],
    [60, 75, 85],
    [90, 95, 88]
])

print("Marks:")
print(marks)

print("\nTotal:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Median:", np.median(marks))

print("\nColumn-wise Sum:")
print(np.sum(marks, axis=0))

print("\nRow-wise Sum:")
print(np.sum(marks, axis=1))

Marks:
[[80 70 90]
 [60 75 85]
 [90 95 88]]

Total: 733
Mean: 81.44444444444444
Minimum: 60
Maximum: 95
Median: 85.0

Column-wise Sum:
[230 240 263]

Row-wise Sum:
[240 220 273]


In [24]:
import numpy as np


students = np.array([
    "Arun",
    "Bala",
    "Chandru",
    "Deepak",
    "Ezhil"
])


marks = np.array([
    [85, 78, 92],
    [67, 72, 80],
    [90, 88, 95],
    [55, 60, 65],
    [76, 85, 82]
])

print("===== STUDENT MARKS ANALYSIS =====\n")

print("Students:")
print(students)

print("\nMarks:")
print(marks)


total_marks = np.sum(marks, axis=1)

print("\nTotal Marks:")
print(total_marks)


average_marks = np.mean(marks, axis=1)

print("\nAverage Marks:")
print(average_marks)


highest_subject = np.max(marks, axis=0)

print("\nHighest Mark in Each Subject:")
print(highest_subject)


lowest_subject = np.min(marks, axis=0)

print("\nLowest Mark in Each Subject:")
print(lowest_subject)


print("\nOverall Highest Mark:")
print(np.max(marks))


print("\nOverall Lowest Mark:")
print(np.min(marks))

print("\nOverall Median:")
print(np.median(marks))


passed_students = students[average_marks >= 75]

print("\nStudents with Average >= 75:")
print(passed_students)


students_below_75 = students[average_marks < 75]

print("\nStudents with Average < 75:")
print(students_below_75)

===== STUDENT MARKS ANALYSIS =====

Students:
['Arun' 'Bala' 'Chandru' 'Deepak' 'Ezhil']

Marks:
[[85 78 92]
 [67 72 80]
 [90 88 95]
 [55 60 65]
 [76 85 82]]

Total Marks:
[255 219 273 180 243]

Average Marks:
[85. 73. 91. 60. 81.]

Highest Mark in Each Subject:
[90 88 95]

Lowest Mark in Each Subject:
[55 60 65]

Overall Highest Mark:
95

Overall Lowest Mark:
55

Overall Median:
80.0

Students with Average >= 75:
['Arun' 'Chandru' 'Ezhil']

Students with Average < 75:
['Bala' 'Deepak']


In [26]:
top_index = np.argmax(total_marks)

print("Top Student:", students[top_index])
print("Total Marks:", total_marks[top_index])
print("Average Marks:", average_marks[top_index])

Top Student: Chandru
Total Marks: 273
Average Marks: 91.0


In [27]:
lowest_index = np.argmin(total_marks)

print("Lowest Student:", students[lowest_index])
print("Total Marks:", total_marks[lowest_index])
print("Average Marks:", average_marks[lowest_index])

Lowest Student: Deepak
Total Marks: 180
Average Marks: 60.0


In [28]:
bonus = np.array([5, 5, 5])

updated_marks = marks + bonus

print("Original Marks:")
print(marks)

print("\nBonus:")
print(bonus)

print("\nUpdated Marks:")
print(updated_marks)

Original Marks:
[[85 78 92]
 [67 72 80]
 [90 88 95]
 [55 60 65]
 [76 85 82]]

Bonus:
[5 5 5]

Updated Marks:
[[ 90  83  97]
 [ 72  77  85]
 [ 95  93 100]
 [ 60  65  70]
 [ 81  90  87]]


In [29]:
print("========== FINAL SUMMARY ==========")

print("Number of Students:", students.size)
print("Number of Subjects:", marks.shape[1])

print("\nTotal Marks of Students:")
for i in range(len(students)):
    print(students[i], ":", total_marks[i])

print("\nAverage Marks:")
for i in range(len(students)):
    print(students[i], ":", average_marks[i])

top_index = np.argmax(total_marks)

print("\nTop Student:", students[top_index])
print("Top Student Total:", total_marks[top_index])
print("Top Student Average:", average_marks[top_index])

print("\nOverall Class Average:", np.mean(marks))

print("\nStudents with Average >= 75:")
print(students[average_marks >= 75])

========== FINAL SUMMARY ==========
Number of Students: 5
Number of Subjects: 3

Total Marks of Students:
Arun : 255
Bala : 219
Chandru : 273
Deepak : 180
Ezhil : 243

Average Marks:
Arun : 85.0
Bala : 73.0
Chandru : 91.0
Deepak : 60.0
Ezhil : 81.0

Top Student: Chandru
Top Student Total: 273
Top Student Average: 91.0

Overall Class Average: 78.0

Students with Average >= 75:
['Arun' 'Chandru' 'Ezhil']
